---
- name: APPLY CONFIGMAP AND SECRETS TO K8S CLUSTER
  hosts: vm
  gather_facts: false

  tasks:
  - name: Copy multiple files to remote server
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - { src: '../../k8s_manifest/configmap.yaml', dest: '/home/ubuntu' }
      - { src: '../../k8s_manifest/secret.yaml', dest: '/home/ubuntu' }

  - name: Apply configmap and secrets to K8S cluster
    ansible.builtin.shell: |
      kubectl apply -f /home/ubuntu/configmap.yaml
      kubectl apply -f /home/ubuntu/secret.yaml