---
- name: SETUP CONFIGMAP AND SECRET FROM db-config.json
  hosts: vm
  gather_facts: false

  tasks:
  - name: CREATE DIRECTORY FOR CONFIGMAP AND SECRET
    ansible.builtin.file:
      path: /home/ubuntu/k8s_configs
      state: directory

  - name: READ db-config.json VARIABLES
    ansible.builtin.include_vars:
      file: ../../db-config.json
      name: db_config

  - name: CREATE ConfigMap FROM db-config.json
    ansible.builtin.template:
        src: "../../configs/configmap.yaml.j2"
        dest: /home/ubuntu/k8s_configs/configmap.yaml
    tags:
      - configmap

  - name: CREATE Secret FROM db-config.json
    ansible.builtin.template:
        src: "../../configs/configsecret.j2"
        dest: /home/ubuntu/k8s_configs/configsecret.yaml
    tags:
      - secret

  - name: APPLY ConfigMap TO Kubernetes
    ansible.builtin.shell:
      cmd: kubectl apply -f /home/ubuntu/k8s_configs/configmap.yaml
    tags:
      - configmap

  - name: APPLY Secret TO Kubernetes
    ansible.builtin.shell:
      cmd: kubectl apply -f /home/ubuntu/k8s_configs/configsecret.yaml
    tags:
      - secret